### ISSUE TITLE
regolith-control-center not installable in jammy due to bad dependency to libwacom2

### ISSUE THREAD

**Issue by ploum** [regolith-linux/voulage#3]
There’s no libwacom2 in Ubuntu Jammy but one package called libwacom9.

As a result, regolith-control-center is not installable in Ubuntu Jammy

**Comment by kgilmer** [comment]
Hi @ploum , thanks for the report.  How did you go about installing Regolith 2 on Jammy?  On my jammy dev instance with `regolith-control-center` installed I'm not seeing a problem [1] nor do I see anywhere it the jammy package that libwacom2 is a dependency [2].  What am I missing?

1: 
![VirtualBox_jammy-test_03_04_2022_10_39_57](https://user-images.githubusercontent.com/49683/161440813-2795eccd-a3e7-4baf-9cc8-7fcc4699ca10.png)

2: https://github.com/regolith-linux/regolith-control-center/blob/ubuntu/jammy/debian/control.in#L46

**Comment by ploum** [comment]
I followed what was on the new website after upgrading to jammy but I discovered the issue : the regolith repo was set to Focal!  Sorry for the noice, error was mine.

**Comment by kgilmer** [comment]
no need to be sorry, thank you for testing!
