### ISSUE TITLE
ilia not installable in Ubuntu jammy

### ISSUE THREAD

**Issue by ploum** [regolith-linux/voulage#4]
Bad dependency for illia an Ubuntu Jammy :

libtracker-sparql-2.0-0

which became 

libtracker-sparql-3-0-X

**Comment by kgilmer** [comment]
As with `regolith-control-center`, I'm curious as to how you got this dependency error.  The jammy version of this package declares the correct dependency:  https://github.com/regolith-linux/ilia/blob/ubuntu/jammy/debian/control#L13

**Comment by ploum** [comment]
I followed what was on the new website after upgrading to jammy but I discovered the issue : the regolith repo was set to Focal!  Sorry for the noice, error was mine.
