### ISSUE TITLE
resizing app-launcher 'Debian 11 Bullseye'

### ISSUE THREAD

**Issue by dev-emre-yildiz** [regolith-linux/voulage#5]
Hi, i pressed two times the '-' button (US keyboard) then app-launcher size decreased. I couldn't find any config in files. Then i removed regolith-desktop a few times. But app-launcher size is the same or regolith runs 'Something went wrong!'. I couldn't find all of the config files and delete them. Some of them are;
- /etc/regolith2
- /usr/share/regolith/
- ~/.config/regolith
- ~/.cache/regolith
How can i succeed to completely uninstall regolith-desktop and reinstall and resize the app-launcher in Debian 11 stable.
All aside the regolith is great. Good work!

**Comment by kgilmer** [comment]
Hi @dev-emre-yildiz , sorry for the mystery!  `ilia` uses `dconf`/`gsettings` for configuration, which is common for gtk applications.  You can see all the config values for `ilia` with `gsettings`, example:

```
$ gsettings list-recursively org.regolith-linux.ilia 
org.regolith-linux.ilia post-launch-sleep 100000
org.regolith-linux.ilia app-launch-counts ...
org.regolith-linux.ilia window-width 552
org.regolith-linux.ilia icon-size 28
org.regolith-linux.ilia window-height 588
```

You can update any of these values using `gsettings reset`, ex:

```
$ gsettings reset org.regolith-linux.ilia window-width
$ gsettings reset org.regolith-linux.ilia window-height
```

You can use the `+` to expand the size of the dialog.

**Comment by dev-emre-yildiz** [comment]
I tried '+' key but somewhat that didn't work. I'll try gsettings option next time. Thx for your reply.
